Table fct_results {
    result_id varchar [primary key]
    race_id varchar [ref: > dim_race.race_id]
    event_id varchar [ref: > dim_event.event_id]
    athlete_id integer [ref: > dim_athlete.athlete_id]
    performance_unit string
    athlete_performance_distance_km double
    athlete_performance_time_h double
    athlete_average_speed double
}

Table dim_event {
    event_id varchar [primary key]
    event_name string
    event_country string
    event_country_name string
    event_unit string
    event_distance_length string
    event_distance_km float
    event_distance_h float
    event_number_of_finishers integer
}

Table dim_race {
    race_id varchar [primary key]
    event_dates date
    year_of_event integer
}

Table dim_athlete {
  athlete_id integer [primary key]
  athlete_year_of_birth integer
  athlete_gender string
  athlete_age_category string
  athlete_country string
  athlete_country_name string
  athlete_club string
  athlete_performance string 
}